export const PROPERTY_TYPES = ['Room', 'Flat', 'Hostel', 'PG']

export const AMENITIES = [
  { id: 'wifi',     label: 'WiFi',     icon: '📶' },
  { id: 'ac',       label: 'AC',       icon: '❄️' },
  { id: 'food',     label: 'Food',     icon: '🍽️' },
  { id: 'parking',  label: 'Parking',  icon: '🅿️' },
  { id: 'laundry',  label: 'Laundry',  icon: '🧺' },
  { id: 'gym',      label: 'Gym',      icon: '🏋️' },
  { id: 'security', label: 'Security', icon: '🔒' },
  { id: 'cctv',     label: 'CCTV',     icon: '📹' },
  { id: 'power',    label: 'Backup Power', icon: '⚡' },
  { id: 'water',    label: '24h Water', icon: '💧' },
]

export const CITIES = [
  { name: 'Mumbai',    emoji: '🌊' },
  { name: 'Delhi',     emoji: '🏛️' },
  { name: 'Bangalore', emoji: '🌿' },
  { name: 'Hyderabad', emoji: '💎' },
  { name: 'Chennai',   emoji: '🌞' },
  { name: 'Pune',      emoji: '🎓' },
  { name: 'Kolkata',   emoji: '🎨' },
  { name: 'Ahmedabad', emoji: '🦁' },
  { name: 'Jaipur',    emoji: '🏰' },
  { name: 'Noida',     emoji: '🏙️' },
]

export const SORT_OPTIONS = [
  { value: 'created_at:desc', label: 'Newest First' },
  { value: 'created_at:asc',  label: 'Oldest First' },
  { value: 'price:asc',       label: 'Price: Low to High' },
  { value: 'price:desc',      label: 'Price: High to Low' },
  { value: 'views:desc',      label: 'Most Popular' },
]

export const MOCK_PROPERTIES = [
  {
    id: '1',
    title: 'Premium Studio near IT Hub',
    description: 'A beautifully furnished studio apartment perfect for working professionals. Fully equipped kitchen, high-speed WiFi, 24/7 security.',
    price: 18000,
    city: 'Bangalore',
    area: 'Koramangala',
    pincode: '560034',
    type: 'Flat',
    amenities: ['wifi', 'ac', 'parking', 'security', 'cctv'],
    availability: true,
    nearby_landmarks: 'Near Forum Mall, 2km from MG Road Metro',
    views: 342,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    landlord: { name: 'Rajesh Kumar', phone: '+91 98765 43210', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh' },
    created_at: '2024-01-15',
  },
  {
    id: '2',
    title: 'Cozy PG for Students',
    description: 'Fully furnished PG accommodation with home-cooked meals included. Walk to university campus.',
    price: 8500,
    city: 'Pune',
    area: 'Kothrud',
    pincode: '411038',
    type: 'PG',
    amenities: ['wifi', 'food', 'laundry', 'security'],
    availability: true,
    nearby_landmarks: 'MIT Campus 500m, Karve Road Market 1km',
    views: 218,
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
    ],
    landlord: { name: 'Priya Sharma', phone: '+91 87654 32109', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya' },
    created_at: '2024-01-20',
  },
  {
    id: '3',
    title: 'Modern 1BHK in Bandra',
    description: 'Stylish 1BHK apartment with sea-facing balcony. Premium furnishing, modular kitchen, gym access.',
    price: 35000,
    city: 'Mumbai',
    area: 'Bandra West',
    pincode: '400050',
    type: 'Flat',
    amenities: ['wifi', 'ac', 'gym', 'parking', 'security', 'cctv'],
    availability: true,
    nearby_landmarks: 'Bandstand 1km, Bandra Station 10 min walk',
    views: 567,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    ],
    landlord: { name: 'Aisha Nair', phone: '+91 76543 21098', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha' },
    created_at: '2024-01-10',
  },
  {
    id: '4',
    title: 'Boys Hostel near AIIMS',
    description: 'Clean and secure hostel for medical students. Attached bathrooms, study room, 24hr power backup.',
    price: 6000,
    city: 'Delhi',
    area: 'Ansari Nagar',
    pincode: '110029',
    type: 'Hostel',
    amenities: ['wifi', 'security', 'power', 'water', 'laundry'],
    availability: true,
    nearby_landmarks: 'AIIMS 200m, INA Market 2km',
    views: 389,
    images: [
      'https://images.unsplash.com/photo-1520166012956-add9ba0835cb?w=800&q=80',
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
    ],
    landlord: { name: 'Mohammed Ali', phone: '+91 65432 10987', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mohammed' },
    created_at: '2024-01-25',
  },
  {
    id: '5',
    title: 'Spacious Room in Shared House',
    description: 'Bright, airy room in a shared 3BHK. Great community, working professional flatmates only.',
    price: 12000,
    city: 'Hyderabad',
    area: 'Gachibowli',
    pincode: '500032',
    type: 'Room',
    amenities: ['wifi', 'ac', 'parking', 'security'],
    availability: true,
    nearby_landmarks: 'DLF Cyber City 1km, ISB Campus 2km',
    views: 145,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    landlord: { name: 'Sunita Reddy', phone: '+91 54321 09876', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sunita' },
    created_at: '2024-02-01',
  },
  {
    id: '6',
    title: 'Girls PG with Homely Food',
    description: 'Safe, hygienic PG for working women. Home-cooked meals 3x daily, strict no-visitor policy, CCTV.',
    price: 9500,
    city: 'Chennai',
    area: 'Velachery',
    pincode: '600042',
    type: 'PG',
    amenities: ['wifi', 'food', 'security', 'cctv', 'laundry', 'water'],
    availability: true,
    nearby_landmarks: 'VIT Chennai 3km, Velachery Station 500m',
    views: 276,
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    landlord: { name: 'Kavitha Menon', phone: '+91 43210 98765', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavitha' },
    created_at: '2024-02-05',
  },
  {
    id: '7',
    title: 'Premium 2BHK near Hinjewadi IT Park',
    description: 'Luxurious 2BHK with modular kitchen, covered parking, and club house access.',
    price: 28000,
    city: 'Pune',
    area: 'Hinjewadi',
    pincode: '411057',
    type: 'Flat',
    amenities: ['wifi', 'ac', 'gym', 'parking', 'security', 'cctv', 'power'],
    availability: true,
    nearby_landmarks: 'Infosys Campus 1km, Wipro 2km, Hinjewadi Phase 2',
    views: 498,
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    ],
    landlord: { name: 'Vikram Desai', phone: '+91 32109 87654', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram' },
    created_at: '2024-01-08',
  },
  {
    id: '8',
    title: 'Student Room near DU North Campus',
    description: 'Affordable room for Delhi University students. Attached bathroom, study table, 24hr electricity.',
    price: 7000,
    city: 'Delhi',
    area: 'Hudson Line',
    pincode: '110009',
    type: 'Room',
    amenities: ['wifi', 'security', 'power', 'water'],
    availability: true,
    nearby_landmarks: 'North Campus 300m, Civil Lines Metro 1km',
    views: 203,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
      'https://images.unsplash.com/photo-1520166012956-add9ba0835cb?w=800&q=80',
    ],
    landlord: { name: 'Anand Gupta', phone: '+91 21098 76543', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anand' },
    created_at: '2024-02-10',
  },
]

export const CAROUSEL_SLIDES = [
  {
    id: 1,
    title: 'Find Your Perfect Stay',
    subtitle: 'Thousands of verified rooms, flats & PGs across India',
    cta: 'Explore Now',
    bg: 'from-brand-400 to-brand-600',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
  },
  {
    id: 2,
    title: 'Students Love GOEAZY',
    subtitle: 'Budget-friendly PGs & hostels near top universities',
    cta: 'Browse PGs',
    bg: 'from-accent-400 to-accent-600',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1400&q=80',
  },
  {
    id: 3,
    title: 'Premium Flats for Professionals',
    subtitle: 'Fully furnished apartments near business districts',
    cta: 'View Flats',
    bg: 'from-purple-400 to-purple-600',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1400&q=80',
  },
]
